2022-04-07 23:38:50,585 ERROR: Exception on /api/users/3/followers [GET] [in /Users/mac/Desktop/Projects/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/mac/Desktop/Projects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mac/Desktop/Projects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/mac/Desktop/Projects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "/Users/mac/Desktop/Projects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'api.get_followers' did not return a valid response. The function either returned None or ended without a return statement.
2022-04-07 23:39:26,552 INFO: Microblog Startup [in /Users/mac/Desktop/Projects/microblog/app/__init__.py:93]
2022-04-07 23:42:24,751 INFO: Microblog Startup [in /Users/mac/Desktop/Projects/microblog/app/__init__.py:93]
2022-04-07 23:42:29,462 ERROR: Exception on /api/users/3/followed [GET] [in /Users/mac/Desktop/Projects/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/mac/Desktop/Projects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mac/Desktop/Projects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/mac/Desktop/Projects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "/Users/mac/Desktop/Projects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'api.get_followed' did not return a valid response. The function either returned None or ended without a return statement.
2022-04-07 23:42:50,565 INFO: Microblog Startup [in /Users/mac/Desktop/Projects/microblog/app/__init__.py:93]
